In [13]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd

train_data = pd.read_csv("C:/Users/biswa/OneDrive/Desktop/0000000000002429_training_titanic_x_y_train.csv")
test_data = pd.read_csv("C:/Users/biswa/OneDrive/Desktop/0000000000002429_test_titanic_x_test.csv")

In [14]:
train_data

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [15]:
test_data

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

In [16]:
train_data['Name']
title_in_train = []

for i in train_data['Name']:
    title_in_train.append(i.split()[1][0:-1])
    
title_in_train = np.array(title_in_train)

title_in_train[title_in_train == "Mr"]=0
title_in_train[title_in_train == "Mrs"]=1
title_in_train[title_in_train == "Miss"]=2
title_in_train[title_in_train == "Master"]=3
title_in_train[(title_in_train != '0')&(title_in_train != '1')&(title_in_train != '2')&(title_in_train != '3')]=4
title_in_train = np.array(title_in_train,dtype =int)
title_in_train

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 4, 1,
       1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 4, 2, 4, 0, 3, 3, 0, 0, 0, 0, 1, 2,
       0, 0, 0, 0, 4, 4, 2, 3, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 4, 1, 4, 1, 0, 1, 0, 2, 0, 0, 0,
       0, 0, 4, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 4,
       2, 1, 0, 2, 0, 0, 0, 0, 2, 2, 1, 4, 2, 2, 2, 0, 0, 0, 0, 1, 0, 2,
       0, 0, 4, 1, 0, 0, 0, 4, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 1, 2,
       1, 0, 1, 0, 2, 1, 1, 2, 0, 0, 0, 4, 0, 0, 0, 3, 0, 4, 1, 0, 4, 2,
       1, 0, 0, 0, 0, 2, 1, 0, 1, 3, 0, 2, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0,
       0, 0, 2, 4, 2, 0, 2, 0, 1, 0, 0, 3, 1, 1, 2, 0, 2, 0, 0, 3, 2, 2,
       2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 3, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 4,
       0, 0, 1, 0, 0, 0, 3, 3, 0, 1, 2, 0, 0, 3, 0, 0, 0, 1, 2, 0, 0, 2,
       2, 0, 0, 0, 2, 0, 0, 2, 1, 2, 3, 0, 0, 2, 0,

In [17]:
test_data['Name']
title_in_test = []

for i in test_data['Name']:
    title_in_test.append(i.split()[1][0:-1])
    
title_in_test = np.array(title_in_test)

title_in_test[title_in_test == "Mr"]=0
title_in_test[title_in_test == "Mrs"]=1
title_in_test[title_in_test == "Miss"]=2
title_in_test[title_in_test == "Master"]=3
title_in_test[(title_in_test != '0')&(title_in_test != '1')&(title_in_test != '2')&(title_in_test != '3')]=4
title_in_test = np.array(title_in_test,dtype =int)
title_in_test

array([3, 4, 0, 1, 0, 0, 4, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 3, 0, 2, 2, 0,
       2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 4, 0,
       2, 3, 0, 2, 0, 0, 0, 2, 1, 2, 0, 0, 3, 0, 0, 0, 0, 4, 1, 2, 1, 4,
       0, 4, 2, 4, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 3, 2, 2, 4, 2, 3, 2, 2, 4, 4, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0,
       2, 0, 0, 2, 0, 3, 0, 2, 1, 2, 2, 0, 0, 0, 1, 2, 1, 4, 2, 0, 2, 0,
       0, 0, 0, 2, 0, 0, 3, 2, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2,
       1, 4, 0, 4, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 4,
       4, 0, 0])

In [18]:
train_data.loc[train_data['Sex']=='female', 'Sex']=0
train_data.loc[train_data['Sex']=='male', 'Sex']=1
train_data.loc[train_data['Embarked'].isnull(), 'Embarked']='S'
train_data.loc[train_data['Embarked']=='S', 'Embarked']=1
train_data.loc[train_data['Embarked']=='C', 'Embarked']=2
train_data.loc[train_data['Embarked']=='Q', 'Embarked']=3
train_data.loc[train_data['Cabin'].isnull(), 'Cabin']=0
train_data.loc[train_data['Cabin']!=0, 'Cabin']=1
train_data.loc[train_data['Age'].isnull(), 'Age']= train_data.loc[train_data['Age'].notnull(), 'Age'].median()
train_data=train_data.drop('Ticket', axis=1)
train_data= train_data.drop('Name', axis=1)

training_data= train_data.values
print(train_data.values)
x = training_data[:, :-1]
y = training_data[:, -1]
y = y.astype('int')
x = np.append(x, title_in_train.reshape(-1, 1), axis=1)
x.shape

[[2 0 29.0 ... 0 1 1]
 [3 1 29.0 ... 0 1 0]
 [2 1 39.0 ... 0 1 0]
 ...
 [3 1 32.0 ... 0 1 1]
 [3 0 22.0 ... 0 1 0]
 [3 0 29.0 ... 0 3 1]]


(668, 9)

In [7]:
test_data.loc[test_data['Sex']=='female', 'Sex']=0
test_data.loc[test_data['Sex']=='male', 'Sex']=1
test_data.loc[test_data['Embarked'].isnull(), 'Embarked']='S'
test_data.loc[test_data['Embarked']=='S', 'Embarked']=1
test_data.loc[test_data['Embarked']=='C', 'Embarked']=2
test_data.loc[test_data['Embarked']=='Q', 'Embarked']=3
test_data.loc[test_data['Cabin'].isnull(), 'Cabin']=0
test_data.loc[test_data['Cabin']!=0, 'Cabin']=1
test_data.loc[test_data['Age'].isnull(), 'Age']=test_data.loc[train_data['Age'].notnull(),'Age'].median()
test_data=test_data.drop('Ticket', axis=1)
test_data= test_data.drop('Name', axis=1)

testing_data=test_data.values
testing_data=np.append(testing_data, title_in_test.reshape(-1, 1), axis=1)
testing_data.shape

(223, 9)

In [8]:
clf=LogisticRegression(solver = 'lbfgs',max_iter=1000000, tol=0.00001)
clf.fit(x, y)

LogisticRegression(max_iter=1000000, tol=1e-05)

In [9]:
predictions =clf.predict(testing_data)

In [10]:
clf.score(x,y)

0.8038922155688623

In [11]:
np.savetxt(X=predictions, delimiter=',', fname='Predictions_titanic.csv', fmt='%.0f')